name: ISS
description: "ISS.AI"

publish_to: "none"

version: 2.0.6+9

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_native_splash: ^2.4.5
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^4.9.0
  sms_autofill: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/users.json
    - assets/data/subscription.json
    - assets/data/payments.json
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/splashLogo.png
    - assets/images/splash.png
    - assets/images/logo1.PNG
    - assets/images/newSplashLogo.png
    - assets/images/iosSplash.jpeg
    - assets/images/ios.png
    - assets/images/android_icon.png

flutter_native_splash:
  color: "#000000"
  android_12:
    icon_background_color: "#000000"

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/ios_icon.png"
  image_path_ios: "assets/images/ios_icon.png"
  remove_alpha_ios: true
